version: "3.8"

services:
  app:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      DATABASE_URL: postgres://app:app@db:5432/app
    volumes:
      - ./:/app:delegated
      - app_node_modules:/app/node_modules
    depends_on:
      - db
    command: sh -c "corepack enable pnpm && pnpm i && pnpm dev -p 3000 -H 0.0.0.0"

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  app_node_modules:
  pg_data: